--- luci-app-advancedplus/Makefile
+++ luci-app-advancedplus/Makefile
@@ -7,7 +7,7 @@ include $(TOPDIR)/rules.mk
 NAME:=advancedplus
 PKG_NAME:=luci-app-$(NAME)
 LUCI_TITLE:=LuCI support for Kucat theme setting by sirpdboy
-LUCI_DEPENDS:=+luci-compat +curl +wget +libustream-openssl
+LUCI_DEPENDS:=+luci-compat +curl
 LUCI_PKGARCH:=all
 
--- a/luci-app-einat/Makefile
+++ b/luci-app-einat/Makefile
@@ -9,7 +9,7 @@ LUCI_NAME:=luci-app-einat
 
 LUCI_TITLE:=LuCI Support for einat
 LUCI_PKGARCH:=all
-LUCI_DEPENDS:=
+LUCI_DEPENDS:=+einat-ebpf
 
 LUCI_DESCRIPTION:=eBPF-based Endpoint-Independent NAT
 
